version: v1.23.12+k3s1
nodes:
- name: server
  targets:
  - ubuntu@10.10.1.91
  type: server
  taints:
  - k3s-controlplane=true:NoExecute
  params:
    no-deploy:
      - traefik
      - servicelb
      - metrics-server
    disable:
      - local-storage
    tls-san:
      - k8s-api.com
secret:
  url: "https://localhost:6443"
  token: "tokenfromfile"
  datastore: "mysql://mysqlfromfile"