{{- if eq .Node.Type "server" -}}
datastore-endpoint: {{ .Secret.DataStore }}
{{- end }}
{{- if eq .Node.Type "agent" -}}
server: {{ .Secret.URL }}
{{- end }}
token: {{ .Secret.Token }}
node-name: {{ .Node.Type }}
with-node-id: true
{{ if .Node.Taints -}}
node-taint:
{{- range .Node.Taints }}
    - {{ . }}
{{- end }}
{{- end }}
{{- if .Node.Labels -}}
node-label:
{{- range .Node.Labels }}
    - {{ . }}
{{- end }}
{{- end }}
{{ .Node.Params | toYaml }}