datastore-endpoint: mysql://mysqlfromfile
token: tokenfromfile
node-name: server
with-node-id: true
node-taint:
    - k3s-controlplane=true:NoExecute
disable:
    - local-storage
no-deploy:
    - traefik
    - servicelb
    - metrics-server
tls-san:
    - k8s-api.com