node-name: server
with-node-id: true
node-taint:
  - k3s-controlplane=true:NoExecute
no-deploy:
  - traefik
  - servicelb
  - metrics-server
disable:
  - local-storage
tls-san: 
  - k8s.lab.takutakahashi.dev
